# Generated by Django 4.0.2 on 2022-03-07 11:31

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('batch', models.IntegerField()),
                ('course', models.CharField(choices=[('btech', 'btech'), ('mtech', 'mtech'), ('phd', 'phd')], max_length=200, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='sites.site')),
            ],
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('department')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=500)),
                ('tech', models.CharField(max_length=200)),
                ('remarks', models.TextField()),
                ('project_type', models.CharField(choices=[('minor', 'minor'), ('major', 'major')], max_length=200, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('ctc', models.IntegerField()),
                ('offer_type', models.CharField(choices=[('onCampus', 'onCampus'), ('offCampus', 'offCampus'), ('ppo', 'ppo')], max_length=200, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('stipend', models.IntegerField()),
                ('intern_type', models.CharField(choices=[('summer', 'summer'), ('six_months', 'six months')], max_length=200, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='students.student')),
            ],
        ),
    ]
