# Generated by Django 4.0.2 on 2022-03-05 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('domain', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InfraImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='infra')),
                ('infra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='infra.infra')),
            ],
        ),
    ]
