# Generated by Django 3.2.8 on 2022-03-07 13:01

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('infra', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='infra',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('department')),
            ],
        ),
        migrations.RemoveField(
            model_name='infra',
            name='domain',
        ),
        migrations.AddField(
            model_name='infra',
            name='department',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='infra', to='sites.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infra',
            name='infra_type',
            field=models.CharField(choices=[('lab', 'lab'), ('library', 'library'), ('lecture_hall', 'lecture hall'), ('seminar_hall', 'seminar hall'), ('other', 'other')], default='1', max_length=200),
            preserve_default=False,
        ),
    ]
