# Generated by Django 4.0.2 on 2022-03-07 11:31

import django.contrib.sites.managers
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('activity', models.CharField(max_length=200)),
                ('given_by', models.CharField(max_length=200)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeptPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('qualification', models.TextField()),
                ('address', models.TextField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('research_profile', models.TextField()),
            ],
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('department')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('international', 'international'), ('national', 'national')], max_length=200, null=True)),
                ('title', models.CharField(max_length=500)),
                ('venue', models.CharField(max_length=200)),
                ('date_start', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_end', models.DateTimeField(auto_now=True)),
                ('designation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('reg_no', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('organization', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('project_type', models.CharField(max_length=200)),
                ('funding_agency', models.CharField(max_length=200)),
                ('date_start', models.DateField(auto_now_add=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=200)),
                ('co_investigator', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('date', models.IntegerField()),
                ('co_authors', models.TextField(null=True)),
                ('publisher', models.CharField(max_length=200)),
                ('citations', models.IntegerField(default=0, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('publication_type', models.CharField(choices=[('book/chapter', 'book/chapter'), ('journal', 'journal'), ('conference', 'conference')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
