# Generated by Django 4.0.2 on 2022-03-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cover_Image',
            field=models.ImageField(default=None, upload_to='activities'),
            preserve_default=False,
        ),
    ]
