# Generated by Django 4.0.2 on 2022-03-03 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityimage',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='activities.activity'),
        ),
    ]
