# Generated by Django 3.2.8 on 2022-03-07 13:01

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('activities', '0003_alter_activityimage_activity'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='activity',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('department')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('stc', 'short term course'), ('workshop', 'workshop'), ('talk', 'expert talks'), ('contest', 'contest'), ('outreach', 'outreach'), ('other', 'other')], default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='department',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='sites.site'),
            preserve_default=False,
        ),
    ]
