<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-03-07 11:31
=======
# Generated by Django 3.2.8 on 2022-03-07 13:01
>>>>>>> d0c2467453fedace0ee29d7421f150a8c4599df6

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='HeroPhotos')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heroPhotos', to='sites.site')),
            ],
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('department')),
            ],
        ),
        migrations.CreateModel(
            name='DeptNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='newsMedia')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='sites.site')),
            ],
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('department')),
            ],
        ),
    ]
