# Generated by Django 4.0.2 on 2022-03-06 11:19

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
                ('department_description', models.CharField(max_length=800)),
                ('vision', models.TextField()),
                ('misison', models.TextField()),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabel', to='sites.site')),
            ],
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('department')),
            ],
        ),
    ]
