# Generated by Django 4.0.2 on 2022-03-07 11:31

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('faculty', '0002_initial'),
        ('whitelabel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelabel',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whitelabel',
            name='hod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.deptperson'),
        ),
        migrations.AddField(
            model_name='whitelabel',
            name='hod_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whitelabel',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whitelabel',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whitelabel',
            name='department',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whitelabel', to='sites.site'),
        ),
        migrations.AlterField(
            model_name='whitelabel',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.CreateModel(
            name='SocietyClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('site', models.URLField(blank=True, null=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='whitelabel.whitelabel')),
            ],
        ),
    ]
