# Generated by Django 3.2.8 on 2022-03-07 13:01

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('whitelabel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelabel',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whitelabel',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whitelabel',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whitelabel',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabel', to='sites.site'),
        ),
        migrations.AlterField(
            model_name='whitelabel',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
